name: docker-wasari-cli

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
      - 'assets/**'
      - 'Wasari.Tvdb*/**'   

extends:
  - tests.yml

jobs:
  docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          tags: redbaty/wasari:latest,redbaty/wasari:b-${{ github.run_number }}
          file: Wasari.Cli/Dockerfile
