FROM alpine:3.15 AS ffmpeg-base
RUN apk update && apk add wget
RUN wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
RUN mkdir /ffmpeg
RUN tar -C /ffmpeg -xvf ffmpeg-master-latest-linux64-gpl.tar.xz --strip-components=1

FROM nvidia/vulkan:1.2.170-470 AS base
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
ENV DEBIAN_FRONTEND=noninteractive 
ENV TZ=Etc/UTC
ENV NO_PROGRESS_BAR=yes

RUN rm -rf /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
RUN rm -rf /usr/lib/x86_64-linux-gnu/libcuda.so.1

# Setup YT-DLP and FFMPEG
RUN apt update && apt install curl python3 python3-pycryptodome wget gnupg2 -y
COPY --from=ffmpeg-base /ffmpeg/bin/ /usr/local/bin/
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
RUN chmod a+rx /usr/local/bin/yt-dlp
RUN chmod a+rx /usr/local/bin/ffmpeg

# Setup Chromium
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable --no-install-recommends
ENV PUPPETEER_EXECUTABLE_PATH "/usr/bin/google-chrome-unstable"

WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "./Wasari/Wasari.csproj" --configuration Release --self-contained -r linux-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -o /app/publish

FROM base AS final
RUN adduser --uid 99 -gid 100 app
WORKDIR /app
RUN chown app -R /app
USER app
COPY --chown=app:100 --from=build /app/publish .
ENTRYPOINT ["./Wasari"]