name: docker-wasari-cli

on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types: 
      - completed

jobs:
  build-and-push-wasari-cli:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          tags: redbaty/wasari:latest,redbaty/wasari:b-${{ github.run_number }}
          file: Wasari.Cli/Dockerfile
